# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ddad1f6f8c3cfe113a5ec8fcd8cfac49edc347092445cdc59f06934312b3ae1efbf9b1ff47e5c905d1dfda63dbbd4f7a59620d5ce905d42b50c2f3f23b45c3bc

test:
  secret_key_base: 23357857c73f452fcda85b9004fbf34ee1a90763c6b02ea2e59484fafff8ef2fb89c48edf473fe81ea704c1d1786ba9681cfec1a307f8c6056d5afc90a26b147

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
